### PR TITLE
Add missing types

### PR DESCRIPTION
**Pull request by davegarred**
Adds missing types to allow client generation by
[openapi-generator](https://github.com/OpenAPITools/openapi-generator).

### To test:
```
docker run --rm -v ./:/local \
  openapitools/openapi-generator-cli \
  generate \
  -g rust \
  -o /local/output_directory \
  -i /local/discord-api-spec/specs/openapi.json
```

### CODE REVIEW

**Comment by thewilloftheshadow** [comment]
@davegarred from the README fyi:
> OpenAPI spec contents are automatically generated, and therefore we do not allow public contributions to this repo.

**Comment by yonilerner** [comment]
The spec is valid as-is. Apparently `openapi-generator` supports 3.1 only in beta (https://github.com/OpenAPITools/openapi-generator#11---compatibility), so that could be why it isn't working here.

Im curious, what error do you get? 

That being said, I will have to close this PR because as already stated, the content is automatically generated so we cannot accept PRs.

**Comment by davegarred** [comment]
Oh I'm just seeing the usual NullPointerException, nothing special for Java but always annoying (and debilitating)
```
  Exception: null
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1269)
	at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:1163)
	at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:609)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:994)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:519)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.NullPointerException
	at org.openapitools.codegen.examples.ExampleGenerator.resolvePropertyToExample(ExampleGenerator.java:228)
	at org.openapitools.codegen.examples.ExampleGenerator.resolveModelToExample(ExampleGenerator.java:352)
	at org.openapitools.codegen.examples.ExampleGenerator.resolvePropertyToExample(ExampleGenerator.java:311)
	at org.openapitools.codegen.examples.ExampleGenerator.resolveModelToExample(ExampleGenerator.java:352)
	at org.openapitools.codegen.examples.ExampleGenerator.generate(ExampleGenerator.java:159)
	at org.openapitools.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:4673)
	at org.openapitools.codegen.languages.AbstractJavaCodegen.fromOperation(AbstractJavaCodegen.java:1750)
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1237)
	... 6 more
```
Basically the wheels come off when it while attempting to create an example and, while looking for a name property, [doesn't find what it's looking for](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/examples/ExampleGenerator.java#L351) and blows up on the following line.

AFAIK openapi-generator is pretty much the default tool, do you have something preferred other than that? If not, what is the workaround?

**Comment by davegarred** [comment]
> @davegarred from the README fyi:
> 
> > OpenAPI spec contents are automatically generated, and therefore we do not allow public contributions to this repo.

Yeah, totally understand the difficulty in working with outside CR's for a project sourced from an internal repo (literally dealing with that currently), but hoping this can point you in the right direction for a proper fix.

**Comment by yonilerner** [comment]
Is this ExampleGenerator used by the generate command in your initial post? 

The validator we use is https://github.com/stoplightio/spectral

I haven't had a chance to look into this yet sorry.

**Comment by davegarred** [comment]
> Is this ExampleGenerator used by the generate command in your initial post?
>
That's correct, the command I used above calls ExampleGenerator and produces the stack trace shown.

That being said, upon further review this definitely appears to be a bug in openapi-generator. A rather big one at that, but I'm guessing no one else is using an empty properties field (I certainly did not realize that was allowed).

**Comment by yonilerner** [comment]
Ah nice. I do think that is the fix here actually. Its unfortunate that we have empty schemas but there are a couple corners of the API that are incredibly tricky to type correctly

**Pull request closed without merging**
